Server:
  RunMode: debug
  HttpPort: 18080
  ReadTimeout: 60
  WriteTimeout: 60
App:
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  Salt: "123456"
Database:
  DBType: sqlite3
  Path: ./var/database.db
Cache:
  Type: redis
  Host: localhost
  Port: "6379"
  Password: ""
  Number: 0